// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: test

#include "../ui.h"

void ui_control_screen_init(void)
{
    ui_control = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_control, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_control, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_control, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imglock = lv_imgbtn_create(ui_control);
    lv_imgbtn_set_src(ui_imglock, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lock_new2_png, NULL);
    lv_obj_set_height(ui_imglock, 64);
    lv_obj_set_width(ui_imglock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_imglock, 128);
    lv_obj_set_y(ui_imglock, 86);
    lv_obj_set_align(ui_imglock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imglock, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_hostsdropdown = lv_dropdown_create(ui_control);
    lv_dropdown_set_options(ui_hostsdropdown,
                            "K8S-1\nK8S-2\nK8S-3\nK8S-4\nMFS-1\nMFS-2\nMFS-3\nMFS-4\nMFSMaster\nK8S Cluster\nMFS Cluster\nRouter\n");
    lv_obj_set_width(ui_hostsdropdown, 180);
    lv_obj_set_height(ui_hostsdropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hostsdropdown, -60);
    lv_obj_set_y(ui_hostsdropdown, -90);
    lv_obj_set_align(ui_hostsdropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hostsdropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_actiondropdown = lv_dropdown_create(ui_control);
    lv_dropdown_set_options(ui_actiondropdown, "Upgrade\nAnsible\nReboot\nShutdown\nCordon\nDrain\n");
    lv_obj_set_width(ui_actiondropdown, 180);
    lv_obj_set_height(ui_actiondropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_actiondropdown, -60);
    lv_obj_set_y(ui_actiondropdown, -50);
    lv_obj_set_align(ui_actiondropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_actiondropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_progressSpinner = lv_spinner_create(ui_control, 1000, 90);
    lv_obj_set_width(ui_progressSpinner, 80);
    lv_obj_set_height(ui_progressSpinner, 80);
    lv_obj_set_x(ui_progressSpinner, 0);
    lv_obj_set_y(ui_progressSpinner, 15);
    lv_obj_set_align(ui_progressSpinner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_progressSpinner, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_progressSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_buttonplay = lv_imgbtn_create(ui_control);
    lv_imgbtn_set_src(ui_buttonplay, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_play2_png, NULL);
    lv_obj_set_width(ui_buttonplay, 80);
    lv_obj_set_height(ui_buttonplay, 80);
    lv_obj_set_x(ui_buttonplay, -112);
    lv_obj_set_y(ui_buttonplay, 13);
    lv_obj_set_align(ui_buttonplay, LV_ALIGN_CENTER);

    ui_completed = lv_img_create(ui_control);
    lv_img_set_src(ui_completed, &ui_img_completed_png);
    lv_obj_set_width(ui_completed, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_completed, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_completed, 0);
    lv_obj_set_y(ui_completed, 15);
    lv_obj_set_align(ui_completed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_completed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_completed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_failed = lv_img_create(ui_control);
    lv_img_set_src(ui_failed, &ui_img_failed_png);
    lv_obj_set_width(ui_failed, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_failed, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_failed, 0);
    lv_obj_set_y(ui_failed, 15);
    lv_obj_set_align(ui_failed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_failed, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_failed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_imglock, ui_event_imglock, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonplay, ui_event_buttonplay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_control, ui_event_control, LV_EVENT_ALL, NULL);

}
