// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: test

#include "../ui.h"

void ui_denied_screen_init(void)
{
    ui_denied = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_denied, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_denied, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_denied, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imageAD = lv_img_create(ui_denied);
    lv_img_set_src(ui_imageAD, &ui_img_access_denied_png);
    lv_obj_set_width(ui_imageAD, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_imageAD, LV_SIZE_CONTENT);    /// 78
    lv_obj_set_align(ui_imageAD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageAD, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imageAD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton1 = lv_imgbtn_create(ui_denied);
    lv_obj_set_height(ui_ImgButton1, 64);
    lv_obj_set_width(ui_ImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton1, 241);
    lv_obj_set_y(ui_ImgButton1, -63);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_imageback = lv_img_create(ui_denied);
    lv_img_set_src(ui_imageback, &ui_img_arrow_png_png);
    lv_obj_set_width(ui_imageback, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_imageback, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_imageback, -95);
    lv_obj_set_y(ui_imageback, -74);
    lv_obj_set_align(ui_imageback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageback, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imageback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_denied, ui_event_denied, LV_EVENT_ALL, NULL);

}
