// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: test

#include "../ui.h"

void ui_keypad_screen_init(void)
{
    ui_keypad = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_keypad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_keypad, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_keypad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textpin = lv_textarea_create(ui_keypad);
    lv_obj_set_width(ui_textpin, 320);
    lv_obj_set_height(ui_textpin, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_textpin, 0);
    lv_obj_set_y(ui_textpin, -100);
    lv_obj_set_align(ui_textpin, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_textpin, "Type PIN");
    lv_textarea_set_one_line(ui_textpin, true);
    lv_textarea_set_password_mode(ui_textpin, true);
    lv_obj_set_style_text_color(ui_textpin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textpin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_textpin, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_textpin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_textpin, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textpin, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);


    ui_keyboard = lv_keyboard_create(ui_keypad);
    lv_keyboard_set_mode(ui_keyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_keyboard, 320);
    lv_obj_set_height(ui_keyboard, 192);
    lv_obj_set_x(ui_keyboard, 0);
    lv_obj_set_y(ui_keyboard, 20);
    lv_obj_set_align(ui_keyboard, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_keyboard, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_keyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_keyboard, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_keyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_keyboard, ui_textpin);
    lv_obj_add_event_cb(ui_keyboard, ui_event_keyboard, LV_EVENT_ALL, NULL);

}
