// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: test

#include "../ui.h"

void ui_main_screen_init(void)
{
    ui_main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KubeLogo = lv_img_create(ui_main);
    lv_img_set_src(ui_KubeLogo, &ui_img_kubernetes_logo_without_workmark_png);
    lv_obj_set_width(ui_KubeLogo, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_KubeLogo, LV_SIZE_CONTENT);    /// 117
    lv_obj_set_x(ui_KubeLogo, 0);
    lv_obj_set_y(ui_KubeLogo, -20);
    lv_obj_set_align(ui_KubeLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KubeLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_KubeLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clustername = lv_label_create(ui_main);
    lv_obj_set_width(ui_clustername, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clustername, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clustername, 0);
    lv_obj_set_y(ui_clustername, 80);
    lv_obj_set_align(ui_clustername, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clustername, "int.pylypiuk.net");
    lv_obj_set_style_text_color(ui_clustername, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clustername, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clustername, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgunlock = lv_imgbtn_create(ui_main);
    lv_imgbtn_set_src(ui_imgunlock, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_unlock_new2_png, NULL);
    lv_obj_set_height(ui_imgunlock, 64);
    lv_obj_set_width(ui_imgunlock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_imgunlock, 125);
    lv_obj_set_y(ui_imgunlock, -84);
    lv_obj_set_align(ui_imgunlock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgunlock, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_imgunlock, ui_event_imgunlock, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_main, ui_event_main, LV_EVENT_ALL, NULL);

}
