// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: test

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_main
void ui_main_screen_init(void);
void ui_event_main(lv_event_t * e);
lv_obj_t * ui_main;
lv_obj_t * ui_KubeLogo;
lv_obj_t * ui_clustername;
void ui_event_imgunlock(lv_event_t * e);
lv_obj_t * ui_imgunlock;


// SCREEN: ui_keypad
void ui_keypad_screen_init(void);
lv_obj_t * ui_keypad;
lv_obj_t * ui_textpin;
void ui_event_keyboard(lv_event_t * e);
lv_obj_t * ui_keyboard;


// SCREEN: ui_denied
void ui_denied_screen_init(void);
void ui_event_denied(lv_event_t * e);
lv_obj_t * ui_denied;
lv_obj_t * ui_imageAD;
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui_imageback;


// SCREEN: ui_control
void ui_control_screen_init(void);
void ui_event_control(lv_event_t * e);
lv_obj_t * ui_control;
void ui_event_imglock(lv_event_t * e);
lv_obj_t * ui_imglock;
lv_obj_t * ui_hostsdropdown;
lv_obj_t * ui_actiondropdown;
lv_obj_t * ui_progressSpinner;
void ui_event_buttonplay(lv_event_t * e);
lv_obj_t * ui_buttonplay;
lv_obj_t * ui_completed;
lv_obj_t * ui_failed;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_lock_new[1] = {&ui_img_lock_new2_png};
const lv_img_dsc_t * ui_imgset_play[1] = {&ui_img_play2_png};
const lv_img_dsc_t * ui_imgset_unlock_new[1] = {&ui_img_unlock_new2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_imgunlock, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_imgunlock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_keypad, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_keypad_screen_init);
    }
}
void ui_event_keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        pin_received(e);
    }
}
void ui_event_denied(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_keypad, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_keypad_screen_init);
    }
}
void ui_event_control(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_imglock, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_imglock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_main_screen_init);
        _ui_flag_modify(ui_imgunlock, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_buttonplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        play_actions(e);
        _ui_flag_modify(ui_progressSpinner, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_completed, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_failed, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_main_screen_init();
    ui_keypad_screen_init();
    ui_denied_screen_init();
    ui_control_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_main);
}
