// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: test

#ifndef _TEST_UI_H
#define _TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../.pio/libdeps/usb/lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_main
void ui_main_screen_init(void);
void ui_event_main(lv_event_t * e);
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_KubeLogo;
extern lv_obj_t * ui_clustername;
void ui_event_imgunlock(lv_event_t * e);
extern lv_obj_t * ui_imgunlock;
// SCREEN: ui_keypad
void ui_keypad_screen_init(void);
extern lv_obj_t * ui_keypad;
extern lv_obj_t * ui_textpin;
void ui_event_keyboard(lv_event_t * e);
extern lv_obj_t * ui_keyboard;
// SCREEN: ui_denied
void ui_denied_screen_init(void);
void ui_event_denied(lv_event_t * e);
extern lv_obj_t * ui_denied;
extern lv_obj_t * ui_imageAD;
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_imageback;
// SCREEN: ui_control
void ui_control_screen_init(void);
void ui_event_control(lv_event_t * e);
extern lv_obj_t * ui_control;
void ui_event_imglock(lv_event_t * e);
extern lv_obj_t * ui_imglock;
extern lv_obj_t * ui_hostsdropdown;
extern lv_obj_t * ui_actiondropdown;
extern lv_obj_t * ui_progressSpinner;
void ui_event_buttonplay(lv_event_t * e);
extern lv_obj_t * ui_buttonplay;
extern lv_obj_t * ui_completed;
extern lv_obj_t * ui_failed;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_kubernetes_logo_without_workmark_png);    // assets\Kubernetes_logo_without_workmark.png
LV_IMG_DECLARE(ui_img_unlock_new2_png);    // assets\unlock_new2.png
LV_IMG_DECLARE(ui_img_access_denied_png);    // assets\access_denied.png
LV_IMG_DECLARE(ui_img_arrow_png_png);    // assets\Arrow_png.png
LV_IMG_DECLARE(ui_img_lock_new2_png);    // assets\lock_new2.png
LV_IMG_DECLARE(ui_img_play2_png);    // assets\play2.png
LV_IMG_DECLARE(ui_img_completed_png);    // assets\completed.png
LV_IMG_DECLARE(ui_img_failed_png);    // assets\failed.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
